### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Flash4433** [ENDERZOMBI102/Decoration-Station#2]
Planned items:
- [ ] Props (Cake, Table with PC...) (Timer)
- [ ] Flora (Timer)
- [ ] Vertical Door (a moving wall?)
- [ ] Horizontal Door (a moving wall?)
- [ ] Observation Room's Glass
- [ ] Normal Door (interactable)
- [ ] Angle Obs Room (3 blocks inside)
- [ ] Angle 4x Obs Room (9 blocks inside?)
